name: CXX CMake CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    ubuntu-build:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
              lto: ["ON", "OFF"]
        env:
            DEBIAN_FRONTEND: noninteractive
            CC: clang-17
            CXX: clang++-17
        steps:
        - name: Checkout
          uses: actions/checkout@v2.0.0
        - name: Setup rust toolchain
          uses: actions-rs/toolchain@v1
          with:
            toolchain: 1.58.0
            override: true
        - run: cargo install cxxbridge-cmd
        - run: sudo apt update
        - run: sudo apt install -y cmake git
        - run: wget https://apt.llvm.org/llvm.sh
        - run: chmod +x ./llvm.sh
        - run: sudo ./llvm.sh 17 17
        - run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_LTO=${{matrix.lto}} ..
        - run: cd build && make
        - run: cd build && ./main
