name: CXX CMake CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    ubuntu-build:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
              lto: ["ON", "OFF"]
        env:
            DEBIAN_FRONTEND: noninteractive
            CC: clang
            CXX: clang++ 
        steps:
        - name: Checkout
          uses: actions/checkout@v2.0.0
        - name: Setup rust toolchain
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable 
            override: true
        - run: cargo install cxxbridge-cmd
        - run: sudo apt update
        - run: sudo apt install -y clang cmake git lld-8
        - run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_LTO=${{matrix.lto}} ..
        - run: cd build && make
        - run: cd build && ./main
